kversion: "3"

services:
  tp5:
    container_name: tp5
    hostname: tp5
    image: aqtiongame/official:v1.0.6
    ports:
      - "27910:27910/udp"
    stdin_open: true
    tty: true
    restart: on-failure:5
    env_file:
     - ./tp5.env
    volumes:
      - /opt/action/logs:/opt/aq2/action/logs
