name: Official AQtion Docker Server (x86)

on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: "Release version tag"
        required: true
      github_repo:
        description: "TNG Github repo"
        required: true
        default: raptor007/aq2-tng
      github_branch:
        description: "TNG Github branch"
        required: true
        default: bots
      docker_image_name:
        description: "Docker image name"
        required: true
        default: "bots"

env:
  CFG_WORKING_DIR: "config"
  TNG_WORKING_DIR: "tng"

jobs:      
  serverfiles_release:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Checkout serverconfigs
        uses: actions/checkout@v3
        with:
          repository: actionquake/serverconfigs
          path: ${{ env.CFG_WORKING_DIR }}

      - name: Checkout TNG
        uses: actions/checkout@v3
        with:
          repository: ${{ github.event.inputs.github_repo }}
          ref: ${{ github.event.inputs.github_branch }}
          path: ${{ env.TNG_WORKING_DIR }}

      - name: Build TNG (Linux x86)
        working-directory: ${{ env.TNG_WORKING_DIR }}
        run: |
          cd source && make -j2 V=1
          cp gamex86_64.so ../../config

      - name: Copy files to parent directory
        working-directory: ${{ env.CFG_WORKING_DIR }}
        run: |
          mv docker/aq2-entrypoint.sh aq2-entrypoint.sh
          mv docker/Dockerfile-ci Dockerfile

      - name: Docker build and push
        working-directory: ${{ env.CFG_WORKING_DIR }}
        run: |
          sed -i "s/_AQTION_VERSION_/${{ github.event.inputs.release_tag }}/g" Dockerfile
          docker build -t aqtiongame/${{ github.event.inputs.docker_image_name }}:${{ github.event.inputs.release_tag }} .
          docker push aqtiongame/${{ github.event.inputs.docker_image_name }}:${{ github.event.inputs.release_tag }}
