name: Official AQtion Docker Server (x86)

on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: "Release version tag"
        required: true

env:
  CFG_WORKING_DIR: "config"

jobs:      
  serverfiles_release:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout serverconfigs
        uses: actions/checkout@v3
        with:
          repository: actionquake/serverconfigs
          path: ${{ env.CFG_WORKING_DIR }}

      - name: Copy files to parent directory
        working-directory: ${{ env.CFG_WORKING_DIR }}
        run: |
          mv docker/aq2-entrypoint.sh aq2-entrypoint.sh
          mv docker/Dockerfile-x86-Linux Dockerfile

      - name: Docker build and push
        working-directory: ${{ env.CFG_WORKING_DIR }}
        run: |
          docker build -t aqtiongame/official:${{ github.event.inputs.release_tag }}
          docker push aqtiongame/official:${{ github.event.inputs.release_tag }}
