name: Official - AQtion Docker Server (x86)

on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: "Release version tag"
        required: true
      q2pro_github_repo:
        description: "Q2Pro Github repo"
        required: true
        default: actionquake/q2pro
      q2pro_github_branch:
        description: "Q2Pro Github branch"
        required: true
        default: aqtion
      tng_github_repo:
        description: "TNG Github repo"
        required: true
        default: actionquake/aq2-tng
      tng_github_branch:
        description: "TNG Github branch"
        required: true
        default: aqtion
      q2admin_github_repo:
        description: "q2admin Github repo"
        required: true
        default: actionquake/q2admin
      q2admin_github_branch:
        description: "q2admin Github branch"
        required: true
        default: aqtion
      docker_image_name:
        description: "Docker image name"
        required: true
        default: "official"

env:
  CFG_WORKING_DIR: "config"
  TNG_WORKING_DIR: "tng"
  Q2A_WORKING_DIR: "q2admin"
  Q2P_WORKING_DIR: "q2pro"

jobs:      
  serverfiles_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout serverconfigs
        uses: actions/checkout@v3
        with:
          repository: actionquake/serverconfigs
          path: ${{ env.CFG_WORKING_DIR }}

      - name: Checkout Q2Pro
        uses: actions/checkout@v3
        with:
          repository: ${{ github.event.inputs.q2pro_github_repo }}
          ref: ${{ github.event.inputs.q2pro_github_branch }}
          path: ${{ env.Q2P_WORKING_DIR }}

      - name: Checkout TNG
        uses: actions/checkout@v3
        with:
          repository: ${{ github.event.inputs.tng_github_repo }}
          ref: ${{ github.event.inputs.tng_github_branch }}
          path: ${{ env.TNG_WORKING_DIR }}

      - name: Checkout q2admin
        uses: actions/checkout@v3
        with:
          repository: ${{ github.event.inputs.q2admin_github_repo }}
          ref: ${{ github.event.inputs.q2admin_github_branch }}
          path: ${{ env.Q2A_WORKING_DIR }}

      - name: Install dependencies
        run: |
            sudo apt-get update
            sudo apt install -y libsdl2-dev libopenal-dev \
            libpng-dev libjpeg-dev zlib1g-dev mesa-common-dev \
            libcurl4-gnutls-dev lua5.1

      - name: Build Q2Pro (Linux x86)
        working-directory: ${{ env.Q2P_WORKING_DIR }}
        run: |
          make -j2 V=1
          cp q2proded ../config/q2proded

      - name: Build TNG (Linux x86)
        working-directory: ${{ env.TNG_WORKING_DIR }}
        run: |
          cd source && make -j2 V=1
          cp gamex86_64.so ../../config/gamex86_64.real.so

      - name: Build q2admin (Linux x86)
        working-directory: ${{ env.Q2A_WORKING_DIR }}
        run: |
          make -j2 V=1
          cp gamex86_64.so ../config/gamex86_64.so

      - name: Copy files to parent directory
        working-directory: ${{ env.CFG_WORKING_DIR }}
        run: |
          mv docker/aq2-entrypoint.sh aq2-entrypoint.sh
          mv docker/Dockerfile-ci Dockerfile

      - name: Copy action files
        working-directory: ${{ env.CFG_WORKING_DIR }}
        run: |
          mkdir action
          mv server/configs/official/config.lua .
          mv server/configs/official/plugins .
          cp -r server/files/tng/ action/
          cp -r server/configs/official/* action/
          cp gamex86_64.real.so action/gamex86_64.real.so
          cp gamex86_64.so action/gamex86_64.so

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker build and push
        working-directory: ${{ env.CFG_WORKING_DIR }}
        run: |
          sed -i "s/_AQTION_VERSION_/${{ github.event.inputs.release_tag }}/g" Dockerfile
          docker build -t aqtiongame/${{ github.event.inputs.docker_image_name }}:${{ github.event.inputs.release_tag }} .
          docker push aqtiongame/${{ github.event.inputs.docker_image_name }}:${{ github.event.inputs.release_tag }}
